server:
  port: 10088
spring:
  application:
    name: client-side-app
  cloud:
    nacos:
      discovery:
        server-addr: 106.54.76.182:8848
    loadbalancer:
      cache:
        # 会使新增实例最多在 ttl 时间内没有流量进入
        ttl: 30s
        # 一个 NamedContextFactory 会消耗一个, 32 已经比较充足
        capacity: 32
logging:
  level:
    cn.liumouren: debug

freeman:
  discovery:
    k8s:
      namespace: api
      mappings:
        api:
          - client-side-app
          - order
        default:
          - user