spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1500
        response-timeout: 3s
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/*/user/**
          metadata:
            namespace: default
        - id: order
          uri: lb://order
          predicates:
            - Path=/*/order/**
          metadata:
            namespace: default
    sentinel:
      filter:
        enabled: false
      scg:
        fallback:
          mode: response
          response-status: 429
          content-type: text/html;charset=utf-8
          response-body: '服务器繁忙, 请稍后再试!'
freeman:
  gateway:
    rules:
      flows:
        - resource: user
          count: 10
        - resource: order
          count: 5
