spring:
  application:
    name: server-side-app
  datasource:
    name: 10098

freeman:
  discovery:
    k8s:
      namespace: api
      mappings:
        api:
          - user
          - order
          - server-side
        gateway:
          - inner-gateway
          - outer-gateway