server:
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    accesslog:
      encoding: UTF-8

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      # 默认将 Date 类型转为时间戳
      WRITE_DATES_AS_TIMESTAMPS: true
  cloud:
    loadbalancer:
      cache:
        capacity: 32

feign:
  okhttp:
    enabled: true
