spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1500
        response-timeout: 3s
      discovery:
        locator:
          enabled: false
    sentinel:
      filter:
        enabled: false
      scg:
        fallback:
          mode: response
          response-status: 429
          content-type: text/html;charset=utf-8
          response-body: '服务器繁忙, 请稍后再试!'
