name: freeman-microservice
on:
  push:
    branches:
      - master
      - dev_*
  pull_request:
    branches:
      - master
jobs:
  compile:
    name: compile & checkstyle & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # maven 缓存
      - name: Dependies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # 编译
      - name: Build with Maven
        run: mvn compile
      # checkstyle
      - name: CheckStyle
        run: mvn checkstyle:check
      # test
      - name: Test
        run: mvn -DskipTests=false test
