name: freeman-microservice
on:
  push:
    branches:
      - master
      - dev_*
  pull_request:
    branches:
      - master
jobs:
  check-compile:
    name: Check whether it can be compiled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn compile